import { Injectable } from '@nestjs/common';
import type { AiConfig } from '~/platform/config/ai.config';
import { AiProvider } from '../app/ports/ai-provider';
import type {
  EmbedTextInput,
  EmbedTextResult,
  GenerateTextInput,
  GenerateTextResult,
  StreamTextEvent,
} from '../app/ai.types';

const FAKE_RESPONSE_TEXT = [
  '# Local fake AI response',
  '',
  'This response is generated by the API fake AI provider for local frontend development.',
  'It is intentionally long so the web app can exercise scroll anchoring, pending states, streaming block rendering, and final-message replacement without calling an external AI provider.',
  '',
  '## What this proves',
  '',
  '- The browser receives multiple network chunks instead of one completed response.',
  '- The chat panel can render a pending assistant turn before the first text delta arrives.',
  '- The message list can keep auto-scroll pinned while new content is appended.',
  '- The user can scroll away from the bottom without the stream stealing their reading position.',
  '- The final persisted turn can replace the temporary streaming message with the same content.',
  '',
  '## Example local answer',
  '',
  'Use this fake stream to test the full frontend behavior: submit a message, watch the answer arrive over time, verify the caret remains visible, copy the completed response, and append the finished assistant text into the active document. The response includes headings, paragraphs, and bullet points because those are the shapes the real normalizer and document preview need to handle.',
  '',
  'No OpenAI, Anthropic, Moonshot, or other remote model is called while `AI_PROVIDER=fake` is active.',
].join('\n');
const FAKE_EMBEDDING_DIMENSIONS = 8;
const STREAM_CHUNK_SIZE = 24;

@Injectable()
export class FakeAiProvider implements AiProvider {
  constructor(private readonly aiConfig: AiConfig) {}

  async generateText(input: GenerateTextInput): Promise<GenerateTextResult> {
    const text = this.resolveResponseText(input);

    return {
      text,
      model: input.model ?? this.aiConfig.defaultTextModel,
      finishReason: 'stop',
    };
  }

  async *streamText(input: GenerateTextInput): AsyncIterable<StreamTextEvent> {
    const text = this.resolveResponseText(input);

    for (let index = 0; index < text.length; index += STREAM_CHUNK_SIZE) {
      await delay(this.aiConfig.fakeStreamDelayMs);
      yield {
        type: 'delta',
        text: text.slice(index, index + STREAM_CHUNK_SIZE),
      };
    }

    yield {
      type: 'done',
      result: {
        text,
        model: input.model ?? this.aiConfig.defaultTextModel,
        finishReason: 'stop',
      },
    };
  }

  async embedText(input: EmbedTextInput): Promise<EmbedTextResult> {
    return {
      embeddings: input.values.map((value) => createFakeEmbedding(value)),
      model: input.model ?? this.aiConfig.defaultEmbeddingModel,
    };
  }

  private resolveResponseText(input: GenerateTextInput): string {
    const prompt = input.prompt ?? input.messages?.at(-1)?.content;

    if (!prompt) {
      return FAKE_RESPONSE_TEXT;
    }

    return `${FAKE_RESPONSE_TEXT}\n\nPrompt received: ${prompt}`;
  }

}

// ---------- Private helpers ----------

function delay(milliseconds: number): Promise<void> {
  if (milliseconds <= 0) {
    return Promise.resolve();
  }

  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

function createFakeEmbedding(value: string): number[] {
  const embedding = Array.from({ length: FAKE_EMBEDDING_DIMENSIONS }, () => 0);

  for (let index = 0; index < value.length; index += 1) {
    const bucket = index % FAKE_EMBEDDING_DIMENSIONS;
    embedding[bucket] += value.charCodeAt(index) / 1000;
  }

  return embedding;
}
